services:
  homelab-lib:
    image: homelab-lib
    ports:
      - "3214:3214"
    volumes:
      - /app/data:/app/data
    environment:
      - DB_PATH=$DB_PATH
      - ARCHIVE_PATH=$ARCHIVE_PATH
      - ADMIN_USERNAME=$ADMIN_USERNAME
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - JWT_SECRET=$JWT_SECRET

